### PR TITLE
Contributors' data through GitHub API and Contributors' Card Design

### PR DESCRIPTION
**Pull request by CA-MKSingh**
Getting contributors' data through GitHub API #7 
Updated the contributors' card design #11

### CODE REVIEW

**Comment by singhnitin77** [comment]
Would be great if we can reduce the height and width of the card, work on flex and grid. 

https://gradientify.com/contributors - similar to this flex and grid accommodating 4 cards in one row + responsive. You can also implement the similar design too for the cards.

**Comment by CA-MKSingh** [comment]
> Would be great if we can reduce the height and width of the card, work on flex and grid.
> 
> https://gradientify.com/contributors - similar to this flex and grid accommodating 4 cards in one row + responsive. You can also implement the similar design too for the cards.

sure

**Comment by CA-MKSingh** [comment]
I have updated the contributors' card design. @singhnitin77  Please have a look at the same.

**Comment by singhnitin77** [comment]
@CA-MKSingh Good job 👏👏, everything looks great.

**Pull request merged**
